name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  ci:
    runs-on: shipfox-2vcpu-ubuntu-2204

    timeout-minutes: 60

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: git checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@3b006c65b880ac90c7894f7d59b892008787cbec # main
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@45a18a69953f27af3c2bfad0a5e01c38ef2da462 # main
      - uses: DeterminateSystems/magic-nix-cache-action@9934a5f127967bcd92e99961e365730ba57253de # main

      - name: Get pnpm store directory
        shell: nix develop --command bash {0}
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # we don't use actions/setup-node because of Nix usage
      - name: Setup pnpm cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install npm dependencies
        shell: nix develop --command bash {0}
        run: pnpm -r install --frozen-lockfile

      - name: Run checks
        shell: nix develop --command bash {0}
        run: pnpm nx run-many -t test -t lint -t build -t typecheck
